# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('author', models.CharField(max_length=25)),
                ('body', models.TextField()),
                ('code', models.CharField(max_length=8)),
                ('lessonId', models.AutoField(primary_key=True, serialize=False)),
                ('modifiedDate', models.DateTimeField()),
                ('thumnbnailImgUrl', models.URLField()),
                ('title', models.TextField()),
                ('uploadedDate', models.DateTimeField()),
            ],
        ),
    ]
