# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171010_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.SmallIntegerField(default=99),
        ),
    ]
