# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lesson_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelId', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('thumbnailImgUrl', models.URLField()),
                ('createdDate', models.DateTimeField()),
                ('modifiedDate', models.DateTimeField()),
            ],
        ),
    ]
