# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='modifiedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
