# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171010_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='uploadedDate',
        ),
    ]
