# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 21:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lesson_uploadeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='levelCollection',
            field=models.CharField(default=(0, 999), max_length=4, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
    ]
