# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 21:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_level_levelcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='levelCollection',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
